inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "google-logging-utils.gemspec"
    - "test/**/*"
Naming/FileName:
  Exclude:
    - "lib/google-logging-utils.rb"

Metrics/ClassLength:
  Max: 200
Metrics/AbcSize:
  Max: 40
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 15
